name: ppet_sop_agent
model: gemini-2.0-flash-001
project_id: work-462617
location: us-central1
datastore_id: your-datastore-id
datastore_kind: Document
rag_corpus: projects/work-462617/locations/us-central1/ragCorpora/4611686018427387904
agent_prompt_id: default